config/routes.rb
require 'sidekiq/web'

TheTable::Application.routes.draw do
  use_doorkeeper

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :reservations
      match "user", to: "users#show"
    end
  end

  resources :reviews
  resources :reservations
  get '/restaurant_reservations', to: 'reservations#restaurant_reservations'
  resources :images
  resources :messages, only: [:new, :create]

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace :api do
    namespace :v1 do
      resources :users
      get '/me' => "credentials#me"
      get '/fast' => 'fast#index'
    end
  end

  resources :restaurants do
    get 'page/:page', action: :index, on: :collection
  end
  
  mount Sidekiq::Web, at: '/sidekiq'

  root :to => 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :lat, :lng, :name, :price, :user_id, :food_style, :description, :city
  belongs_to :user
  has_many :reviews
  has_many :reservations
  has_many :chats
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :authenticate_user!
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])
    @user = User.find(@restaurant.user_id)
    @images = Image.where(user_id: @user.id)
    @reviews = @restaurant.reviews
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    # authorize! :new, @restaurant

    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    # authorize! :edit, @restaurant

    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
    user = User.find(current_user.id)
    user.restaurant_id = @restaurant.id
    user.save

  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => { :class => 'form-horizontal' } do |f| %>
  
  <div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :city, ["London", "Edinburgh"] %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lng, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lng, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lat, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lat, :class => 'text_field' %>
    </div>

  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :food_style, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :food_style, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                restaurants_path, :class => 'btn' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/restaurants/index.html.erb
<%- model_class = Restaurant -%>
<div ng-controller="mapController" class="container-fluid">
  <div>
    <div ng-if="hello" id="map_canvas">
      <google-map center="map.center", zoom="map.zoom", options="options">
        <marker ng-repeat="restaurant in restaurants | filter:search:strict" coords="{ latitude: restaurant.lat, longitude: restaurant.lng}" idkey="restaurant.id" options="{ visible: restaurant.hide }">
          <marker-label content="restaurant.name" anchor="2 0"/>
        </marker>
      </google-map>
    </div>

    <div class="well well-lg" ng-show="boo">
      City: <input id="radio_1" ng-model="search.city" type="radio" name="city" value="London"> London <input id="radio_2" ng-model="search.city" type="radio" name="city" value="Edinburgh"> Edinburgh<br><br>
      Name: <input id="search_name" ng-model="search.name" /><br><br>
      Food Style:<select id="search_select" ng-model="search.food_style">
        <option ng-repeat="style in food_styles" value="{{style}}">{{style}}</option>
      </select><br><br>
      Average Price: <input id="search_price" ng-keyup="numSearch()" ng-model="nums" />
    </div>

    <div ng-if="hello" ng-hide="boo">
      <a class='btn btn-primary' href="" ng-click="showSearch()">Search</a>
    </div>

    <div ng-hide="hello">
      <div class="well well-lg">
        <h1>Hello <%= current_user.username%>!</h1>
        <h4>
          Bare with me a wee minute while the map loads.  It will be with you shortly.  Please contact the Restaurant with any questions and if you wish to add your establishment please contact the website Admin.
        </h4>

      </div>
    </div>

    <div ng-if="hello" class="continer-fluid">
      <div class="col-md-8">
        <table class="table table-striped">
          <thead>
            <tr>
              <th><%= model_class.human_attribute_name(:name) %></th>
              <th><%= model_class.human_attribute_name(:average_price_per_meal) %></th>
              <th><%= model_class.human_attribute_name(:distance) %></th>
            </tr>
          </thead>
          <tbody>
            <tr ng-repeat="restaurant in restaurants | filter:search:strict | filter:matchAmount | orderBy: 'distance' | startFrom:currentPage*pageSize | limitTo:pageSize" ng-click="selectRestaurant(restaurant)" ng-show="restaurant.hide">
              <td>{{ restaurant.name }}</td>
              <td>£{{ restaurant.price }}</td>
              <td>{{ restaurant.distance }}km</td>
            </tr>
          </tbody>
        </table>

        <button ng-disabled="currentPage == 0" ng-click="currentPage=currentPage-1">Previous</button>
        {{currentPage+1}}/{{numberOfPages()}}
        <button ng-disabled="currentPage >= restaurants.length/pageSize - 1" ng-click="currentPage=currentPage+1">Next</button>
        </div>
      </div>
      <div class="col-md-4">
        <div class="well well-lg" ng-show="selectedRestaurant">
          <a class='btn btn-primary close' href="/restaurants/{{selectedRestaurant.id}}">Show</a>
          Name: {{ selectedRestaurant.name }}<br>
          Average Price: £{{ selectedRestaurant.price }}<br>
          Distance: {{ selectedRestaurant.distance }} km<br>
          Food Style: {{selectedRestaurant.food_style}}<br>
        </div>
      </div>
    </div>


  </div>
  </br>
  </br>
</div>

app/views/restaurants/new.html.erb
<div ng-controller="findController" class="ng-scope">

<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<a id="find_me" class='btn btn-primary' href="" ng-click="pleaseFindMe()">Find Me!</a>
<%= render :partial => 'form' %>

</div>

app/views/restaurants/show.html.erb
<% model_class = Restaurant %>
<div ng-controller="restController">
<div class="well well-sm">
  <div class="page-header">
    <h1><%= @restaurant.name %></h1>
  </div>

  <div class="jumbotron">
    <%= image_tag @images.first.picture_url %>
  </div>


  <dl class="dl-horizontal">
  <br>
    <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
    <dd><%= @restaurant.price %></dd>
    <dt><strong><%= model_class.human_attribute_name(:food_style) %>:</strong></dt>
    <dd><%= @restaurant.food_style %></dd>
    <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
    <dd><%= @restaurant.description %></dd>
  </dl>

  <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Email</button>
  <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal_two">Reserve a Table</button>
  <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal_three">Reveiw</button>
  <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal_four">More Images</button>
</div>

<% if @reviews %>
  <% @reviews.each do |review| %>
    <div class="well well-sm">
      <h3><%= review.title %></h3>
      <h6><%= review.created_at.to_s(:long) %></h6>
      <p><%= review.review %></p>
    </div>
  <% end %>   
<% end %>
  <div style="display: none" class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
          <h4 class="modal-title" id="myModalLabel">Email the Restaurant</h4>
        </div>
        <div class="modal-body">
          <%= form_tag messages_path, method: :post do %>
            <%= hidden_field_tag :user_id, current_user.id %>
            <%= hidden_field_tag :restaurant_id, @restaurant.id %>
            <%= text_area_tag :content %><br>
            <%= submit_tag %>
            <% end %>
        </div>
      </div>
    </div>
  </div>


  <div style="display: none" class="modal fade" id="myModal_two" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
          <h4 class="modal-title" id="myModalLabel">Reserve a Table</h4>
        </div>
        <div class="modal-body">
          <%= form_tag reservations_path, method: :post do %>
            <%= hidden_field_tag :user_id, current_user.id %>
            <%= hidden_field_tag :restaurant_id, @restaurant.id %>        
            <input type="date" id="date" name="date"></input>
            <input type="time" id="start_time" name="start_time"></input>
            <%= label_tag :seats %>
            <%= number_field_tag :seats %><br>
            <%= submit_tag %>
          <% end %>

        </div>
      </div>
    </div>
  </div>

  <div style="display: none" class="modal fade" id="myModal_three" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
          <h4 class="modal-title" id="myModalLabel">Review this Restaurant</h4>
        </div>
        <div class="modal-body">
          <%= form_tag reviews_path, method: :post do %>
            <%= hidden_field_tag :user_id, current_user.id %>
            <%= hidden_field_tag :restaurant_id, @restaurant.id %>
            <%= label_tag :title %>
            <%= text_field_tag :title %><br>
            <%= label_tag :review %>
            <%= text_area_tag :review %><br>
            <%= submit_tag %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
  

  <div style="display: none" class="modal fade" id="myModal_four" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
          <h4 class="modal-title" id="myModalLabel">Restaurant Images</h4>
        </div>
        <div class="modal-body">
          <ul class="thumbnails">
            <% @images.each do |image| %>
            <li class="span4">
              <%= image_tag image.picture_url %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>