config/routes.rb
require 'sidekiq/web'

TheTable::Application.routes.draw do
  use_doorkeeper

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :reservations
      match "user", to: "users#show"
    end
  end

  resources :reviews
  resources :reservations
  get '/restaurant_reservations', to: 'reservations#restaurant_reservations'
  resources :images
  resources :messages, only: [:new, :create]

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace :api do
    namespace :v1 do
      resources :users
      get '/me' => "credentials#me"
      get '/fast' => 'fast#index'
    end
  end

  resources :restaurants do
    get 'page/:page', action: :index, on: :collection
  end
  
  mount Sidekiq::Web, at: '/sidekiq'

  root :to => 'restaurants#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="theTable">
<head>
  <title>TheTable</title>
  <script src="//maps.googleapis.com/maps/api/js?libraries=weather,geometry,visualization&sensor=false&language=en&v=3.14"></script>


  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">The Table</a>
        <div class="nav-collapse">
          <ul class="nav">
            <% if user_signed_in? %>
              <% if current_user.restaurant %>
                <li><%= link_to "Edit your Restaurant", edit_restaurant_path(current_user.restaurant) %></li>
                <li><%= link_to "Add images", images_path %></li>
                <li><%= link_to "Your Restaurant Reservations", restaurant_reservations_path %></li>
              <% elsif current_user.role == "manager" %>
                <li><%= link_to "Add your Restaurant", new_restaurant_path %></li>
              <% end %>
              <li><a href="/reservations">Your Reservations</a></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown">Account<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= current_user.username %></li>
                  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                  <li><a href="mailto:jwchristie.jc@gmail.com">Email Admin</a></li>
                  <li class="divider"></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <% if notice %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">×</a>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">×</a>
      <%= alert %>
    </div>
  <% end %>
  
  <%= yield %>

</body>
</html>